spring.application.name=tree-pruning

# ─── PostgreSQL ───────────────────────────────────────────────────────────────
# POSTGRES_HOST, POSTGRES_USER y POSTGRES_PASSWORD los inyecta Infisical en producción.
# En local: define estas variables de entorno apuntando al servidor vía túnel SSH.
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1023
#spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_BD}
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ─── JPA / Hibernate ──────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}
spring.jpa.properties.hibernate.default_schema=${JPA_SCHEMA:treepruning}
spring.jpa.open-in-view=false

# ─── Server ───────────────────────────────────────────────────────────────────
#server.port=${SERVER_PORT:8080}
